---
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: BIDIRECTIONAL
  
- ros_topic_name: "/saye/odometry_with_covariance"
  gz_topic_name: "/model/saye/odometry_with_covariance"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.OdometryWithCovariance"
  direction: GZ_TO_ROS

- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

- ros_topic_name: "/tf"
  gz_topic_name: "/model/saye/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera/front_raw"
  gz_topic_name: "/camera_front"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# - ros_topic_name: "/imu"
#   gz_topic_name: "/imu"
#   ros_type_name: "sensor_msgs/msg/Imu"
#   gz_type_name: "gz.msgs.IMU"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/joint_states"
#   gz_topic_name: "/world/saye/model/saye/joint_state"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "gz.msgs.Model"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/camera/left_raw"
#   gz_topic_name: "/camera_left"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "gz.msgs.Image"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/camera/right_raw"
#   gz_topic_name: "/camera_right"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "gz.msgs.Image"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/camera/rear_raw"
#   gz_topic_name: "/camera_rear"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "gz.msgs.Image"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/real_sense/image_raw"
#   gz_topic_name: "/rs_front/image"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "gz.msgs.Image"
#   direction: GZ_TO_ROS
# - ros_topic_name: "/imu"
#   gz_topic_name: "/imu"
#   ros_type_name: "sensor_msgs/msg/Imu"
#   gz_type_name: "gz.msgs.IMU"
#   direction: GZ_TO_ROS
# - ros_topic_name: "real_sense/depth_image"
#   gz_topic_name: "/rs_front/depth_image"
#   ros_type_name: "sensor_msgs/msg/Image"
#   gz_type_name: "gz.msgs.Image"
#   direction: GZ_TO_ROS
# - ros_topic_name: "real_sense/depth_point"
#   gz_topic_name: "/rs_front/points"
#   ros_type_name: "sensor_msgs/msg/PointCloud2"
#   gz_type_name: "gz.msgs.PointCloudPacked"
#   direction: GZ_TO_ROS